🔀 :: (#10) login modal 퍼블리싱
MoonMinJeong/PSS pull request #11
Opened 2022-10-23 14:24 UTC by hyeyeonchurros

2022-10-23 23:29 UTC, paperdeer requested changes

2022-10-23 23:29 UTC, paperdeer commented on src/components/login/Button.tsx
> +            <img src={img} />
alt요소 추가해주세요

2022-10-23 23:29 UTC, paperdeer commented on src/components/login/LoginModal.tsx
> +        </_ModalBackground>
모달 닫는것도 추가해주세요

2022-10-23 23:29 UTC, paperdeer commented on src/components/login/LoginModal.tsx
> +                <img src={CloseIcon.src} />
이거 x버튼인거 같은데 _ContentContainer위에 위치시켜 주세요

2022-10-24 00:19 UTC, hyeyeonchurros commented on src/components/login/LoginModal.tsx
> +        </_ModalBackground>
그거 헤더 다 만들어지면 열리는 거랑 같이 할게요

2022-10-24 02:55 UTC, paperdeer commented on src/components/login/LoginModal.tsx
> +        </_ModalBackground>
옙

2022-10-24 02:55 UTC, paperdeer approved these changes

2022-10-24 02:59 UTC, merged