🔀 :: 게시글 작성 api 연동
MoonMinJeong/PSS pull request #33
Opened 2022-11-14 08:36 UTC by ipiyou

2022-11-16 14:31 UTC, hyeyeonchurros requested changes

2022-11-16 14:31 UTC, hyeyeonchurros commented on src/models/createPost/request.ts
> +}
헉 나 이거 만들어 놨는데 src/model/notice/request.ts 가보면 있어

2022-11-21 10:14 UTC, paperdeer approved these changes

2022-11-21 10:16 UTC, hyeyeonchurros approved these changes
좋았습니당

2022-11-21 10:16 UTC, merged