🔀:: (#5) 소개글 작성 퍼블리싱
MoonMinJeong/PSS pull request #6
Opened 2022-09-29 06:49 UTC by ipiyou

2022-09-29 14:02 UTC, hyeyeonchurros approved these changes

2022-09-29 14:02 UTC, hyeyeonchurros commented
수고했어

2022-09-29 14:19 UTC, hyeyeonchurros requested changes

2022-09-29 14:19 UTC, hyeyeonchurros commented on src/components/common/Input.tsx
> +            />
여기 부분 매개변수를 다 받아오니까 <_inputElement {...props} /> 로 해주라

2022-09-29 14:19 UTC, hyeyeonchurros commented on src/components/common/Input.tsx
> +    height: ${props => props.height};
여기 font-size: ${({inputFontSize})=> inputFontSize} 이렇게 다 바꾸면 좋을 것 같은뎅...

2022-10-03 13:29 UTC, hyeyeonchurros commented on src/components/write/InputSession.tsx
> +    attend: [];
타입 정의 개마렵네요^^7

2022-10-03 13:29 UTC, hyeyeonchurros commented on src/components/write/InputSession.tsx
> +    contend: string;
contend -> content로 수정 바랍니다

2022-10-04 02:05 UTC, paperdeer commented on src/components/write/TagInput.tsx
> +    setValue?: (e: ChangeEvent<HTMLInputElement>, name: string) => void;
옵셔널로 받은 이유가 있어요?

2022-10-04 02:05 UTC, paperdeer commented on src/components/write/footMenu.tsx
> +            </div>
div보다는 button의 역할을 하는것 같아요

2022-10-11 00:00 UTC, paperdeer commented on src/components/write/Editor/index.tsx
> +const NoSsrEditor = dynamic(() => import('./Setting'), { ssr: false });
이게 뭔지 모르겠어요

2022-10-11 00:00 UTC, paperdeer commented on src/components/write/Editor/index.tsx
> +const NoSsrEditor = dynamic(() => import('./Setting'), { ssr: false });
아 No SSR Editor 인가??

2022-11-12 06:22 UTC, paperdeer approved these changes

2022-11-13 14:00 UTC, hyeyeonchurros approved these changes
태완님 개개개잘하시네요 UI쪽 살짝 아쉬운 부분만... 나중에.... 수정해주세요 찡찡

2022-11-14 07:55 UTC, merged